/**
 * Counselor Summary PDF (PDFKit, Letter, Helvetica).
 */

const PDFDocument = require('pdfkit');

const NAVY = '#1a1f36';
const CORAL = '#e85d3a';
const TEAL = '#0d9488';
const AMBER = '#d97706';
const RED = '#dc2626';
const ROW_GRAY = '#f8f9fb';
const MUTED = '#6b7280';

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 50;
const CONTENT_W = PAGE_W - 2 * MARGIN;
const FOOTER_Y = PAGE_H - 38;
const CONTENT_BOTTOM = FOOTER_Y - 18;

/** Mirrors insightPostProcess.js DIM_KEYWORDS for weakness ↔ dimension matching */
const DIM_KEYWORDS = {
  academic: ['gpa', 'grade', 'transcript', 'course', 'rigor', 'ap ', ' ib', 'sat', 'act', 'class', 'academic', 'school'],
  activities: ['extracurricular', 'activity', 'club', 'sport', 'volunteer', 'leadership', 'officer', 'president', 'captain', 'team'],
  honors: ['award', 'honor', 'scholar', 'recognition', 'medal', 'prize'],
  narrative: ['essay', 'personal statement', 'writing', 'story', 'voice', 'narrative', 'reflection'],
  institutionalFit: ['fit', 'major', 'campus', 'culture', 'mission', 'institution', 'university', 'program', 'computer science'],
};

const DIMENSION_ROWS = [
  { field: 'academicStrength', insight: 'academic', label: 'Academic Strength' },
  { field: 'activityImpact', insight: 'activities', label: 'Activity Impact' },
  { field: 'honorsAwards', insight: 'honors', label: 'Honors & Awards' },
  { field: 'narrativeStrength', insight: 'narrative', label: 'Narrative Strength' },
  { field: 'institutionalFit', insight: 'institutionalFit', label: 'Institutional Fit' },
];

function inferDimensions(text) {
  const t = ` ${String(text).toLowerCase()} `;
  const hits = [];
  for (const [dim, kws] of Object.entries(DIM_KEYWORDS)) {
    if (kws.some((k) => t.includes(k))) hits.push(dim);
  }
  return hits.length ? hits : null;
}

function textRelatesToInsight(text, insightKey) {
  const dims = inferDimensions(text);
  if (dims && dims.includes(insightKey)) return true;
  return false;
}

function scoreTextColor(score) {
  if (score >= 7.0) return TEAL;
  if (score >= 4.0) return AMBER;
  return RED;
}

function scoreFillRgb(score) {
  if (score >= 7.0) return { r: 13, g: 148, b: 136 };
  if (score >= 4.0) return { r: 217, g: 119, b: 6 };
  return { r: 220, g: 38, b: 38 };
}

function cellRect(doc, x, y, w, h, fillColor, strokeColor = '#e5e7eb') {
  doc.save();
  doc.fillColor(fillColor).rect(x, y, w, h).fill();
  doc.strokeColor(strokeColor).lineWidth(0.35).rect(x, y, w, h).stroke();
  doc.restore();
}

function drawScoreFillRect(doc, x, y, w, h, score) {
  const { r, g, b } = scoreFillRgb(score);
  doc.save();
  doc.opacity(0.1);
  doc.rect(x, y, w, h).fill(`rgb(${r},${g},${b})`);
  doc.restore();
}

function drawFooter(doc, pageNum) {
  doc.save();
  doc.font('Helvetica').fontSize(8).fillColor(MUTED);
  doc.text('Generated by Admitly | useadmitly.com', MARGIN, FOOTER_Y, {
    width: CONTENT_W * 0.65,
    lineBreak: false,
  });
  doc.font('Helvetica').fontSize(8).fillColor(MUTED);
  doc.text(`Page ${pageNum}`, MARGIN, FOOTER_Y, {
    width: CONTENT_W,
    align: 'right',
    lineBreak: false,
  });
  doc.restore();
}

function ensureSpace(doc, y, needed, pageState) {
  if (y + needed <= CONTENT_BOTTOM) return y;
  drawFooter(doc, pageState.num);
  pageState.num += 1;
  doc.addPage();
  return MARGIN;
}

function formatScore(score) {
  const n = typeof score === 'number' ? score : 0;
  return (Math.round(n * 10) / 10).toFixed(1);
}

function bandLabel(band) {
  const b = String(band || '').toLowerCase();
  if (b === 'reach') return 'REACH';
  if (b === 'safety') return 'SAFETY';
  return 'TARGET';
}

function overallAssessmentSentence(evaluations) {
  const reachNames = evaluations
    .filter((e) => String(e.band || '').toLowerCase() === 'reach')
    .map((e) => e.university)
    .filter(Boolean);
  if (reachNames.length === 0) {
    return 'This student is competitive across their target schools.';
  }
  const list = reachNames.join(', ');
  return `This student faces selective admissions at ${list} — strategic improvement in key dimensions could strengthen their positioning.`;
}

function dimensionAverages(evaluations) {
  const out = {};
  for (const { field, insight } of DIMENSION_ROWS) {
    let sum = 0;
    for (const e of evaluations) {
      sum += typeof e[field] === 'number' ? e[field] : 0;
    }
    out[insight] = evaluations.length ? sum / evaluations.length : 0;
  }
  return out;
}

function topWeaknessForInsight(evaluations, insightKey) {
  const field = DIMENSION_ROWS.find((d) => d.insight === insightKey)?.field || 'alignmentScore';
  const sorted = [...evaluations].sort((a, b) => (a[field] ?? 0) - (b[field] ?? 0));
  for (const ev of sorted) {
    for (const w of ev.weaknesses || []) {
      if (typeof w === 'string' && textRelatesToInsight(w, insightKey)) return w;
    }
  }
  const first = sorted[0];
  if (first && Array.isArray(first.weaknesses) && first.weaknesses[0]) return String(first.weaknesses[0]);
  return 'Review evaluation weaknesses for this dimension.';
}

function impactLevel(avg) {
  const gap = 7.0 - avg;
  if (gap > 3) return 'High';
  if (gap >= 1.5) return 'Medium';
  return 'Low';
}

function insightLabel(insight) {
  const row = DIMENSION_ROWS.find((d) => d.insight === insight);
  return row ? row.label : insight;
}

function pickStrengthForInsight(ev, insightKey) {
  const list = (ev.strengths || []).filter((s) => typeof s === 'string');
  for (const s of list) {
    if (textRelatesToInsight(s, insightKey)) return s;
  }
  return list[0] || '—';
}

function pickWeaknessForInsight(ev, insightKey) {
  const list = (ev.weaknesses || []).filter((s) => typeof s === 'string');
  for (const w of list) {
    if (textRelatesToInsight(w, insightKey)) return w;
  }
  return list[0] || '—';
}

function dimensionWithLargestSpread(evaluations) {
  let best = null;
  for (const { field, label } of DIMENSION_ROWS) {
    const scores = evaluations.map((e) => (typeof e[field] === 'number' ? e[field] : 0));
    const min = Math.min(...scores);
    const max = Math.max(...scores);
    const spread = max - min;
    if (spread >= 2 && (!best || spread > best.spread)) {
      const minIdx = scores.indexOf(min);
      const maxIdx = scores.indexOf(max);
      best = {
        label,
        min,
        max,
        spread,
        minSchool: evaluations[minIdx]?.university || 'School',
        maxSchool: evaluations[maxIdx]?.university || 'School',
      };
    }
  }
  return best;
}

function patternsBullets(evaluations) {
  const bullets = [];
  const avgs = dimensionAverages(evaluations);
  const entries = Object.entries(avgs);
  if (entries.length === 0) return bullets;

  const sortedHigh = [...entries].sort((a, b) => b[1] - a[1]);
  const sortedLow = [...entries].sort((a, b) => a[1] - b[1]);
  const [hiKey, hiVal] = sortedHigh[0];
  const [loKey, loVal] = sortedLow[0];
  bullets.push(`Strongest dimension: ${insightLabel(hiKey)} (avg ${formatScore(hiVal)})`);
  bullets.push(`Largest gap: ${insightLabel(loKey)} (avg ${formatScore(loVal)})`);

  const bestVar = dimensionWithLargestSpread(evaluations);
  if (bestVar) {
    bullets.push(
      `Note: ${bestVar.label} varies significantly across schools (${formatScore(bestVar.min)} at ${bestVar.minSchool} vs ${formatScore(bestVar.max)} at ${bestVar.maxSchool}) — consider school-specific essay tailoring.`
    );
  }
  return bullets.slice(0, 3);
}

function drawPage1(doc, data, pageState) {
  let y = MARGIN;
  doc.save();
  doc.font('Helvetica-Bold').fontSize(10).fillColor(CORAL);
  doc.text('ADMITLY', MARGIN, y, { width: CONTENT_W * 0.45, align: 'left', characterSpacing: 1.2 });
  doc.font('Helvetica-Bold').fontSize(14).fillColor(NAVY);
  doc.text('Counselor Summary', MARGIN, y, { width: CONTENT_W, align: 'right' });
  doc.restore();
  y += 20;
  doc.font('Helvetica').fontSize(10).fillColor(NAVY);
  doc.text(data.generatedDate || '', MARGIN, y, { width: CONTENT_W, align: 'right' });
  y += 22;
  doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).lineWidth(1).strokeColor(CORAL).stroke();
  doc.strokeColor(NAVY);
  y += 16;

  doc.font('Helvetica-Bold').fontSize(12).fillColor(NAVY);
  doc.text('Student Profile', MARGIN, y);
  y += 18;
  const displayName = data.studentName || 'Student';
  doc.font('Helvetica-Bold').fontSize(16).fillColor(NAVY);
  doc.text(displayName, MARGIN, y, { width: CONTENT_W });
  y += doc.heightOfString(displayName, { width: CONTENT_W }) + 6;
  doc.font('Helvetica').fontSize(11).fillColor(NAVY);
  const p = data.profile || {};
  const lines = [
    `GPA: ${formatScore(typeof p.gpa === 'number' ? p.gpa : 0)}`,
    `Intended major: ${p.intendedMajor || '—'}`,
    `AP courses: ${p.apCoursesTaken ?? 0} taken / ${p.apCoursesAvailable ?? 0} available`,
  ];
  if (typeof p.satScore === 'number') lines.push(`SAT: ${p.satScore}`);
  if (typeof p.actScore === 'number') lines.push(`ACT: ${p.actScore}`);
  for (const line of lines) {
    y = ensureSpace(doc, y, 16, pageState);
    doc.text(line, MARGIN, y, { width: CONTENT_W });
    y += 14;
  }
  y += 10;

  y = ensureSpace(doc, y, 24, pageState);
  doc.font('Helvetica-Bold').fontSize(12).fillColor(NAVY);
  doc.text('Application Snapshot', MARGIN, y);
  y += 16;
  doc.font('Helvetica').fontSize(11).fillColor(NAVY);
  doc.text(
    `Activities: ${p.activitiesCount ?? 0} · Leadership roles: ${p.leadershipRoles ?? 0} · Honors: ${p.honorsCount ?? 0}`,
    MARGIN,
    y,
    { width: CONTENT_W }
  );
  y += 28;

  y = ensureSpace(doc, y, 24, pageState);
  doc.font('Helvetica-Bold').fontSize(12).fillColor(NAVY);
  doc.text('Schools Evaluated', MARGIN, y);
  y += 16;
  for (const ev of data.evaluations || []) {
    y = ensureSpace(doc, y, 36, pageState);
    doc.font('Helvetica-Bold').fontSize(11).fillColor(NAVY);
    doc.text(ev.university || 'School', MARGIN, y, { width: CONTENT_W - 120 });
    const align = typeof ev.alignmentScore === 'number' ? formatScore(ev.alignmentScore) : '—';
    doc.font('Helvetica-Bold').fontSize(11).fillColor(scoreTextColor(ev.alignmentScore));
    doc.text(`${align}/10`, MARGIN + CONTENT_W - 100, y, { width: 100, align: 'right' });
    y += 14;
    doc.font('Helvetica').fontSize(9).fillColor(NAVY);
    doc.text(bandLabel(ev.band), MARGIN, y, { characterSpacing: 0.8 });
    y += 18;
  }
  y += 8;

  y = ensureSpace(doc, y, 40, pageState);
  doc.font('Helvetica-Bold').fontSize(12).fillColor(NAVY);
  doc.text('Overall Assessment', MARGIN, y);
  y += 16;
  doc.font('Helvetica').fontSize(11).fillColor(NAVY);
  const assess = overallAssessmentSentence(data.evaluations || []);
  doc.text(assess, MARGIN, y, { width: CONTENT_W, align: 'left' });
}

function drawSingleSchoolDetail(doc, ev, pageState) {
  let y = MARGIN;
  doc.font('Helvetica-Bold').fontSize(14).fillColor(NAVY);
  const title = `Detailed Evaluation: ${ev.university || 'School'}`;
  doc.text(title, MARGIN, y, { width: CONTENT_W });
  y += 28;

  for (const { field, insight, label } of DIMENSION_ROWS) {
    const score = ev[field];
    const sc = typeof score === 'number' ? score : 0;
    y = ensureSpace(doc, y, 52, pageState);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(NAVY);
    doc.text(label, MARGIN, y, { width: CONTENT_W });
    y += 14;
    doc.font('Helvetica-Bold').fontSize(11).fillColor(scoreTextColor(sc));
    doc.text(`${formatScore(sc)}/10`, MARGIN, y);
    const barX = MARGIN + 80;
    const barW = 140;
    const barH = 8;
    const fillW = (Math.max(0, Math.min(10, sc)) / 10) * barW;
    doc.save();
    doc.fillColor('#e5e7eb').rect(barX, y - 2, barW, barH).fill();
    doc.fillColor(scoreTextColor(sc)).rect(barX, y - 2, fillW, barH).fill();
    doc.strokeColor('#d1d5db').lineWidth(0.5).rect(barX, y - 2, barW, barH).stroke();
    doc.restore();
    y += 18;
    doc.font('Helvetica').fontSize(9).fillColor(NAVY);
    doc.text(`Strength: ${pickStrengthForInsight(ev, insight)}`, MARGIN + 10, y, { width: CONTENT_W - 10 });
    y += 12;
    doc.text(`Weakness: ${pickWeaknessForInsight(ev, insight)}`, MARGIN + 10, y, { width: CONTENT_W - 10 });
    y += 20;
  }

  y = ensureSpace(doc, y, 40, pageState);
  doc.font('Helvetica-Bold').fontSize(10).fillColor(NAVY);
  doc.text('Alignment Score', MARGIN, y);
  doc.font('Helvetica-Bold').fontSize(11).fillColor(scoreTextColor(ev.alignmentScore));
  doc.text(`${formatScore(ev.alignmentScore)}/10`, MARGIN + 120, y);
  const barX = MARGIN + 200;
  const barW = 140;
  const barH = 8;
  const sc = typeof ev.alignmentScore === 'number' ? ev.alignmentScore : 0;
  const fillW = (Math.max(0, Math.min(10, sc)) / 10) * barW;
  doc.save();
  doc.fillColor('#e5e7eb').rect(barX, y - 2, barW, barH).fill();
  doc.fillColor(scoreTextColor(sc)).rect(barX, y - 2, fillW, barH).fill();
  doc.strokeColor('#d1d5db').lineWidth(0.5).rect(barX, y - 2, barW, barH).stroke();
  doc.restore();
}

function drawComparisonTable(doc, evaluations, pageState) {
  let y = MARGIN;
  doc.font('Helvetica-Bold').fontSize(14).fillColor(NAVY);
  doc.text('Cross-School Comparison', MARGIN, y, { width: CONTENT_W });
  y += 24;

  const schools = evaluations.map((e) => e.university || 'School');
  const dimColW = 118;
  const n = schools.length;
  const cellW = (CONTENT_W - dimColW) / n;
  const rowH = 22;
  const headerH = 28;

  y = ensureSpace(doc, y, headerH + rowH * 7 + 8, pageState);

  let x = MARGIN;
  doc.save();
  doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY);
  cellRect(doc, x, y, dimColW, headerH, ROW_GRAY);
  doc.fillColor(NAVY);
  doc.text('Dimension', x + 4, y + 8, { width: dimColW - 8 });
  x += dimColW;
  for (let i = 0; i < n; i++) {
    const alt = i % 2 === 0 ? ROW_GRAY : '#ffffff';
    cellRect(doc, x, y, cellW, headerH, alt);
    doc.fillColor(NAVY);
    const name = schools[i].length > 22 ? `${schools[i].slice(0, 20)}…` : schools[i];
    doc.font('Helvetica-Bold').fontSize(7);
    doc.text(name, x + 3, y + 6, { width: cellW - 6, align: 'center' });
    x += cellW;
  }
  doc.restore();
  y += headerH;

  const rows = [...DIMENSION_ROWS.map((d) => ({ label: d.label, field: d.field, bold: false })), { label: 'Alignment Score', field: 'alignmentScore', bold: true }];

  let rowIdx = 0;
  for (const row of rows) {
    y = ensureSpace(doc, y, rowH + 4, pageState);
    x = MARGIN;
    const bg = rowIdx % 2 === 0 ? '#ffffff' : ROW_GRAY;
    cellRect(doc, x, y, dimColW, rowH, bg);
    doc.fillColor(NAVY);
    doc.font(row.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(8);
    doc.text(row.label, x + 4, y + 6, { width: dimColW - 8 });
    x += dimColW;
    for (let i = 0; i < n; i++) {
      const ev = evaluations[i];
      const score = typeof ev[row.field] === 'number' ? ev[row.field] : 0;
      drawScoreFillRect(doc, x, y, cellW, rowH, score);
      doc.rect(x, y, cellW, rowH).strokeColor('#e5e7eb').lineWidth(0.3).stroke();
      doc.font(row.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9).fillColor(scoreTextColor(score));
      doc.text(formatScore(score), x, y + 6, { width: cellW, align: 'center' });
      x += cellW;
    }
    y += rowH;
    rowIdx += 1;
  }

  y += 16;
  doc.font('Helvetica-Bold').fontSize(11).fillColor(NAVY);
  doc.text('Patterns', MARGIN, y);
  y += 14;
  doc.font('Helvetica').fontSize(10).fillColor(NAVY);
  for (const b of patternsBullets(evaluations)) {
    y = ensureSpace(doc, y, 28, pageState);
    doc.fillColor(NAVY).circle(MARGIN + 3, y + 4, 1.5).fill();
    doc.fillColor(NAVY).font('Helvetica').fontSize(10);
    doc.text(b, MARGIN + 12, y, { width: CONTENT_W - 12, align: 'left' });
    y += doc.heightOfString(b, { width: CONTENT_W - 12 }) + 6;
  }
}

function drawPage3(doc, data, pageState) {
  let y = MARGIN;
  doc.font('Helvetica-Bold').fontSize(14).fillColor(NAVY);
  doc.text('Strategic Priorities', MARGIN, y, { width: CONTENT_W });
  y += 26;

  const evaluations = data.evaluations || [];
  const avgs = dimensionAverages(evaluations);
  const sortedGaps = Object.entries(avgs).sort((a, b) => a[1] - b[1]);
  const top3 = sortedGaps.slice(0, 3);

  for (const [insight, avg] of top3) {
    y = ensureSpace(doc, y, 70, pageState);
    doc.font('Helvetica-Bold').fontSize(11).fillColor(NAVY);
    doc.text(`${insightLabel(insight)} — avg ${formatScore(avg)}/10`, MARGIN, y);
    y += 14;
    doc.font('Helvetica').fontSize(10).fillColor(NAVY);
    doc.text(`Impact: ${impactLevel(avg)}`, MARGIN, y);
    y += 14;
    const weak = topWeaknessForInsight(evaluations, insight);
    const weakLine = `Top weakness: ${weak}`;
    doc.text(weakLine, MARGIN, y, { width: CONTENT_W });
    y += doc.heightOfString(weakLine, { width: CONTENT_W }) + 12;
  }

  y += 8;
  const strongDims = Object.entries(avgs).filter(([, v]) => v >= 7.0);
  if (strongDims.length > 0) {
    y = ensureSpace(doc, y, 40, pageState);
    doc.font('Helvetica-Bold').fontSize(12).fillColor(NAVY);
    doc.text('Already Strong — Protect These', MARGIN, y);
    y += 16;
    doc.font('Helvetica').fontSize(10).fillColor(TEAL);
    for (const [k, v] of strongDims) {
      y = ensureSpace(doc, y, 16, pageState);
      doc.text(`${insightLabel(k)}: ${formatScore(v)}/10 avg`, MARGIN, y, { width: CONTENT_W });
      y += 14;
    }
  }

  const essays = data.essayAnalyses || [];
  if (essays.length > 0) {
    y += 10;
    y = ensureSpace(doc, y, 36, pageState);
    doc.font('Helvetica-Bold').fontSize(12).fillColor(NAVY);
    doc.text('Essay Performance by School', MARGIN, y);
    y += 18;

    const colSchool = 130;
    const colNum = 52;
    const tableW = CONTENT_W;
    const rowH = 20;
    y = ensureSpace(doc, y, rowH + 8, pageState);
    let x = MARGIN;
    doc.save();
    doc.font('Helvetica-Bold').fontSize(7).fillColor(NAVY);
    cellRect(doc, x, y, colSchool, rowH, ROW_GRAY);
    doc.text('School', x + 3, y + 6, { width: colSchool - 6 });
    x += colSchool;
    for (const h of ['Strategic', 'Content', 'Structure', 'Verdict']) {
      const w = h === 'Verdict' ? tableW - colSchool - 3 * colNum : colNum;
      cellRect(doc, x, y, w, rowH, ROW_GRAY);
      doc.text(h, x + 2, y + 6, { width: w - 4, align: 'center' });
      x += w;
    }
    doc.restore();
    y += rowH;

    for (const ea of essays) {
      const verdict = String(ea.overallVerdict || '').slice(0, 100);
      y = ensureSpace(doc, y, rowH + 4, pageState);
      x = MARGIN;
      doc.font('Helvetica').fontSize(7).fillColor(NAVY);
      cellRect(doc, x, y, colSchool, rowH, '#ffffff');
      doc.text((ea.university || '—').slice(0, 28), x + 3, y + 5, { width: colSchool - 6 });
      x += colSchool;
      const nums = [
        typeof ea.strategicFit === 'number' ? formatScore(ea.strategicFit) : '—',
        typeof ea.contentAnalysis === 'number' ? formatScore(ea.contentAnalysis) : '—',
        typeof ea.structureAndVoice === 'number' ? formatScore(ea.structureAndVoice) : '—',
      ];
      for (const num of nums) {
        cellRect(doc, x, y, colNum, rowH, '#ffffff');
        doc.text(num, x, y + 6, { width: colNum, align: 'center' });
        x += colNum;
      }
      const vw = tableW - colSchool - 3 * colNum;
      cellRect(doc, x, y, vw, rowH, '#ffffff');
      doc.text(verdict || '—', x + 3, y + 4, { width: vw - 6 });
      y += rowH;
    }
  }
}

function drawPage4(doc, data, pageState) {
  let y = MARGIN;
  doc.font('Helvetica-Bold').fontSize(14).fillColor(NAVY);
  doc.text('Discussion Guide for Counselor Meeting', MARGIN, y, { width: CONTENT_W });
  y += 20;
  doc.font('Helvetica').fontSize(10).fillColor(NAVY);
  doc.text(
    'The following questions are generated from this student\'s specific evaluation data. Each references a concrete data point from their profile.',
    MARGIN,
    y,
    { width: CONTENT_W }
  );
  y += doc.heightOfString(
    'The following questions are generated from this student\'s specific evaluation data. Each references a concrete data point from their profile.',
    { width: CONTENT_W }
  ) + 16;

  const guide = data.discussionGuide || [];
  if (guide.length === 0) {
    y = ensureSpace(doc, y, 40, pageState);
    doc.font('Helvetica').fontSize(10).fillColor(NAVY);
    doc.text(
      'Discussion guide could not be generated. Use the comparison matrix and priority actions above as meeting talking points.',
      MARGIN,
      y,
      { width: CONTENT_W }
    );
    return;
  }

  guide.forEach((item, idx) => {
    y = ensureSpace(doc, y, 56, pageState);
    doc.font('Helvetica-Bold').fontSize(11).fillColor(NAVY);
    doc.text(`${idx + 1}. ${item.question || ''}`, MARGIN, y, { width: CONTENT_W });
    y += doc.heightOfString(`${idx + 1}. ${item.question || ''}`, { width: CONTENT_W }) + 6;
    doc.font('Helvetica').fontSize(10).fillColor(NAVY);
    doc.text(`Context: ${item.context || ''}`, MARGIN, y, { width: CONTENT_W });
    y += doc.heightOfString(`Context: ${item.context || ''}`, { width: CONTENT_W }) + 4;
    doc.font('Helvetica-Oblique').fontSize(8).fillColor(MUTED);
    doc.text(`Based on: ${item.dataPoint || ''}`, MARGIN, y, { width: CONTENT_W });
    y += doc.heightOfString(`Based on: ${item.dataPoint || ''}`, { width: CONTENT_W }) + 14;
  });
}

/**
 * @param {object} data
 * @returns {Promise<Buffer>}
 */
function generateCounselorPDF(data) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({
      size: 'LETTER',
      margin: MARGIN,
      autoFirstPage: true,
    });

    doc.on('data', (c) => chunks.push(c));
    doc.on('error', reject);
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    const pageState = { num: 1 };

    try {
      drawPage1(doc, data, pageState);
      drawFooter(doc, pageState.num);
      pageState.num += 1;
      doc.addPage();

      const evs = data.evaluations || [];
      if (evs.length === 1) {
        drawSingleSchoolDetail(doc, evs[0], pageState);
      } else {
        drawComparisonTable(doc, evs, pageState);
      }
      drawFooter(doc, pageState.num);
      pageState.num += 1;
      doc.addPage();

      drawPage3(doc, data, pageState);
      drawFooter(doc, pageState.num);
      pageState.num += 1;
      doc.addPage();

      drawPage4(doc, data, pageState);
      drawFooter(doc, pageState.num);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = {
  generateCounselorPDF,
};
